system:
  title: 'もぐもぐ'
  url: 'https://mogumogu.com/'
  bbs_url: 
  trello_url: 
  google_form_url: 
  official_twitter_id: 'newburu'
  description: 'みんなのもぐもぐを投稿しよう！'
  description_smartphone: 'もぐもぐ！！'
  hashtag: 'もぐもぐ'
  keywords: ['Twitter', 'おやつ', 'もぐもぐ']
  twitter_site: newburu
  twitter:
    url: 'https://twitter.com/'
    tweet_url: 'http://twitter.com/intent/tweet'
    share_url: 'http://twitter.com/share'
  facebook:
    share_url: 'https://www.facebook.com/share.php'
  line:
    share_url: 'https://social-plugins.line.me/lineit/share'
  mail:
    share_url: 'mailto:'
  default:
    user_name: 名無しさん
  const:
    on_str: 'on'
    off_str: 'off'